<a href="https://colab.research.google.com/github/kishoredage/letter_recognizer/blob/main/sentiment__analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/IMDB Dataset.csv', engine='python', on_bad_lines='skip')

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Text Cleaning

1. Sample 10000 rows

2.Removing html tags

3.Remove special characters

4.converting every thing to lower case

5. Removing stop words

6. stemming

In [6]:
df = df.sample(10000)

In [7]:
df.shape

(10000, 2)

In [8]:
 df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

/tmp/ipykernel_5303/3545590690.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)
/tmp/ipykernel_5303/3545590690.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [9]:
df.head()

                                                  review  sentiment
15381  This movie, quite literally, does not have one...          0
42     Of all the films I have seen, this one, The Ra...          0
24632  OK...ths film (like Segal's last few films) on...          1
14179  Im not a big Tim Matheson fan but i have to ad...          1
15744  A group of friends come face-to-face with a fa...          0

In [10]:
import re
clean = re.compile('<.*?>')
re.sub(clean,'',df.iloc[2].review)

'OK...ths film (like Segal\'s last few films) once again goes beyond the "knock \'em down, kick \'em in the groin, shoot \'em in the face, get revenge against the bad guys for hurting my sister\'s niece\'s cousin" stuff Seagal was into for a while. Geepers, Steven started thinking, and using his bucks to make movies with actual ideas in them. SURE....there is plenty of action in this flick, but also some thought and heart. It\'s not an Oscar flick, but well worth the effort, unless the viewer is so into brain dead violence that it hurts to have to think for longer than a second. It\'s worth a rental..or two!!'

In [12]:
# function to clean html tags
def clean_html(text):
  clean = re.compile('<.*?>')
  return re.sub(clean,'',text)

In [13]:
df['review'] = df['review'].apply(clean_html)

In [14]:
# Converting everything to lower
def convert_lower(text):
  return text.lower()

In [15]:
df['review'].apply(convert_lower)

15381    this movie, quite literally, does not have one...
42       of all the films i have seen, this one, the ra...
24632    ok...ths film (like segal's last few films) on...
14179    im not a big tim matheson fan but i have to ad...
15744    a group of friends come face-to-face with a fa...
                               ...
35201    i don't see that much wrong with this movie. g...
219      ed wood rides again. the fact that this movie ...
5135     not funny - how can anyone link this to monty ...
19342    if you enjoy riddles and suspense, you will en...
24500    four teenage girls in a suburb of los angeles ...
Name: review, Length: 10000, dtype: object

In [20]:
# function to remove special characters

def remove_special(text):
  x = ''
  for i in text:
      if i.isalnum():
         x = x+i
      else:
        x= x+ ' '
  return x

In [21]:
df['review'].apply(remove_special)

15381    This movie  quite literally  does not have one...
42       Of all the films I have seen  this one  The Ra...
24632    OK   ths film  like Segal s last few films  on...
14179    Im not a big Tim Matheson fan but i have to ad...
15744    A group of friends come face to face with a fa...
                               ...
35201    I don t see that much wrong with this movie  G...
219      Ed Wood rides again  The fact that this movie ...
5135     Not funny   how can anyone link this to Monty ...
19342    If you enjoy riddles and suspense  you will en...
24500    Four teenage girls in a suburb of Los Angeles ...
Name: review, Length: 10000, dtype: object

In [22]:
# Remove stopwords
import nltk

In [23]:
from nltk.corpus import stopwords

In [25]:
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [29]:
def remove_stopwords(text):
  x = []

  for i in text.split():
    if i not in stopwords.words('english'):
      x.append(i)

  y=x[:]
  x.clear()
  return y

In [30]:
df['review'] = df['review'].apply(remove_stopwords)

In [33]:
# performing stemming

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [31]:
y = []
def stem_words(text):
  for i in text:
    y.append(ps.stem(i))

  z = y[:]
  y.clear()
  return z

In [35]:
stem_words(['I','loved','loving','IT'])

['i', 'love', 'love', 'it']

In [38]:
df['review'] = df['review'].apply(stem_words)

In [39]:
# join back
def join_back(list_input):
  return " ".join(list_input)

In [48]:
df['review'] = df['review'].apply(join_back)

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [49]:
x = cv.fit_transform(df['review']).toarray()

In [50]:
y = df.iloc[:,-1].values

In [52]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [54]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [55]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [56]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)
clf3.fit(x_train,y_train)

BernoulliNB()

In [58]:
y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)
y_pred3 = clf3.predict(x_test)

In [59]:
from sklearn.metrics import*

In [60]:
print('Gaussian',accuracy_score(y_test,y_pred1))
print('Multinomial',accuracy_score(y_test,y_pred2))
print('Bernoulli',accuracy_score(y_test,y_pred3))

Gaussian 0.6295
Multinomial 0.836
Bernoulli 0.8265